{{- if .Values.rbac.create -}}
apiVersion: {{ include "helpers.helpers.rbac.apiVersion" . }}
kind: ClusterRoleBinding
metadata:
  name: api-k8s-registry-access-{{ include "helpers.helpers.fullname.namespace" . }}
  labels: {{- include "helpers.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- .Values.commonAnnotations | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: {{ include "helpers.helpers.rbac.apiVersion" . }}
  kind: ClusterRole
  name: api-k8s-registry-access-{{ include "helpers.helpers.fullname.namespace" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "helpers.helpers.serviceAccountName" . }}
  namespace: {{ include "helpers.helpers.fullname.namespace" . }}
{{ end }}