apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helpers.helpers.fullname" . }}-cm
  namespace: {{ include "helpers.helpers.namespace" . | quote }}
data:
  {{- range $key, $value := .Values.configmap.data }}
    {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}