apiVersion: {{ include "helpers.helpers.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "helpers.helpers.fullname" . }}
  namespace: {{ include "helpers.helpers.namespace" . | quote }}
  labels: {{- include "helpers.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- .Values.commonAnnotations | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  {{- if .Values.updateStrategy }}
  strategy: {{- toYaml .Values.updateStrategy | nindent 4 }}
  {{- end }}
  {{- $podLabels := dict "commonLabels" ( merge .Values.podLabels .Values.commonLabels ) "context" $ ) }}
  selector:
    matchLabels: {{- include "helpers.labels.matchLabels" ( dict "customLabels" $podLabels "context" $ ) | nindent 6 }}
  template:
    metadata:
      labels: {{- include "helpers.labels.standard" ( dict "customLabels" $podLabels "context" $ ) | nindent 8 }}
      annotations:
        {{- if .Values.podAnnotations }}
        {{- .Values.podAnnotations | nindent 8 }}
        {{- end }}
        {{- if and .Values.metrics.enabled .Values.metrics.podAnnotations }}
        {{- .Values.metrics.podAnnotations ) | nindent 8 }}
        {{- end }}
    spec:
      {{- include "helpers.images.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ template "apim.serviceAccountName" . }}
      {{- if .Values.hostAliases }}
      hostAliases: {{- .Values.hostAliases | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity: {{- .Values.affinity ) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "helpers.affinities.pods" (dict "type" .Values.podAffinityPreset "customLabels" $podLabels "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "helpers.affinities.pods" (dict "type" .Values.podAntiAffinityPreset "customLabels" $podLabels "context" $) | nindent 10 }}
        nodeAffinity: {{- include "helpers.affinities.nodes" (dict "type" .Values.nodeAffinityPreset.type "key" .Values.nodeAffinityPreset.key "values" .Values.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- if .Values.dnsPolicy  }}
      dnsPolicy: {{ .Values.dnsPolicy }}
      {{- end }}
      {{- if .Values.dnsConfig }}
      dnsConfig: {{- .Values.dnsConfig | nindent 8 }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector: {{- .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{- .Values.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.schedulerName }}
      schedulerName: {{ .Values.schedulerName | quote }}
      {{- end }}
      {{- if .Values.podSecurityContext.enabled }}
      securityContext: {{- .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      {{- if .Values.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- end }}
      {{- if .Values.containerSecurityContext.enabled }}
     
      containers:
        - name: {{ include "helpers.helpers.fullname" . }}
          image: {{ include "apim.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          {{- if .Values.containerSecurityContext.enabled }}
          securityContext: {{- .Values.containerSecurityContext | nindent 12 }}
          {{- end }}
          {{- if .Values.command }}
          command: {{- .Values.command | nindent 12 }}
          {{- end }}
          {{- if .Values.args }}
          args: {{- .Values.args | nindent 12 }}
          {{- end }}
          {{- if .Values.lifecycleHooks }}
          lifecycle: {{- .Values.lifecycleHooks | nindent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "helpers.helpers.fullname" . }}-cm
            {{- if .Values.envVarsSecret }}
            - secretRef:
                name: {{ .Values.envVarsSecret }}
            {{- end }}
          ports:
            {{- if .Values.containerPorts.http }}
            - name: http
              containerPort: {{ .Values.containerPorts.http }}
            {{- end }}
            {{- if .Values.containerPorts.https }}
            - name: https
              containerPort: {{ .Values.containerPorts.https }}
            {{- end }}
            {{- if .Values.extraContainerPorts }}
            {{- .Values.extraContainerPorts | nindent 12 }}
            {{- end }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe: 
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: {{ ternary "https" "http" (and (empty .Values.containerPorts.http) (not (empty .Values.containerPorts.https))) }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe: 
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: {{ ternary "https" "http" (and (empty .Values.containerPorts.http) (not (empty .Values.containerPorts.https))) }}
          {{- end }}
          {{- if .Values.resources }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
          - name: config
            mountPath: {{ required .Values.persistence.volumeMountPath | nindent 12 }}
          {{- if .Values.persistence.additionalMounts }}
            {{- .Values.persistence.additionalMounts | toYaml | nindent 12 }}
          {{- end }}
      volumes:
      - name: config
        {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingClaim | default (include "helpers.helpers.fullname" .) }}
        {{- else }}
        emptyDir: { }
        {{- end }}
        {{- if .Values.persistence.additionalVolumes }}
            {{- .Values.persistence.additionalVolumes | toYaml | nindent 8}}
        {{- end }}
        {{- if .Values.volumes }}
        {{- .Values.volumes | nindent 8 }}
        {{- end }}