{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: {{ include "helpers.helpers.pvc.apiVersion" . }}
metadata:
  name: {{ include "helpers.helpers.fullname" . }}
  labels:
    {{- include "helpers.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
spec:
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  volumeName: {{ .Values.persistence.volumeName | quote }}
  volumeMode: {{ .Values.persistence.volumeMode | quote }}
{{- end }}
