{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helpers.helpers.serviceAccountName" . }}
  namespace: {{ include "helpers.helpers.namespace" . | quote }}
  labels: {{- include "helpers.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.serviceAccount.Annotations }}
  annotations: {{- .Values.serviceAccount.Annotations | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}